FROM python:3.9-slim
RUN apt-get update && apt-get install -y ffmpeg --no-install-recommends && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . .
RUN chmod +r cookies.txt
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "main.py"]
